---
title: "phylosig_bpe"
author: "Zach Hopton"
date: "2024-08-14"
output: html_document
---

# Testing for Phylogenetic Signal from BPE token productivity (and related measures)

```{r}
#get the necessary libraries
library(phytools)
library(ape)
```

```{r}
#visualize our tree
tree <- read.nexus(file="../data/tree_a2/mcc.trees")
```

```{r}
plotTree(tree,fsize=0.4)
```

```{r}
#Load the character data
file="../data/text_stats/lang_vecs_standardized.tsv"
char <- read.delim(file)

#change a few language names so they correspond to the languages in reference tree
char[2,"lang"] <- "Tosk"
char[3,"lang"] <- "Eastern_Armenian"
char[9,"lang"] <- "Persian"
char[11,"lang"] <- "Scots_Gaelic"
char[13,"lang"] <- "Modern_Greek"
char[30,"lang"] <- "Slovenian"
char[33,"lang"] <- "Ukrainian"
```

```{r}
#Isolate the relevant statistics
productivity <- setNames(char$standardized_p,
                         char$lang)
cumulative_freq <- setNames(char$standardized_cf,
                         char$lang)
idiosyncrasy <- setNames(char$standardized_i,
                         char$lang)
entropy <- setNames(char$standardized_h,
                         char$lang)
redundancy <- setNames(char$standardized_r,
                         char$lang)
```


```{r}
#Calculate Blomberg's K for each of our continuous variables
K.prod <- phylosig(tree,productivity,
                   test=TRUE)
K.id <- phylosig(tree,idiosyncrasy,
                   test=TRUE)
K.cf <- phylosig(tree,cumulative_freq,
                   test=TRUE)
K.h <- phylosig(tree,entropy,
                   test=TRUE)
K.r <- phylosig(tree,redundancy,
                   test=TRUE)
```
```{r}
print(K.prod)
```
```{r}
print(K.id)
```
```{r}
#Significant#
print(K.cf)
```

```{r}
plot(K.cf)
```

```{r}
#Significant#
print(K.h)
plot(K.h)
```

```{r}
#Significant#
print(K.r)
plot(K.r)
```
## Robustness testing: How do these results compare when using another reference tree?

```{r}
tree_a3 <-read.nexus(file="../data/tree_a3/mcc.trees")
```

```{r}
#Calculate Blomberg's K for each of our continuous variables
K.prod_a3 <- phylosig(tree_a3,productivity,
                   test=TRUE)
K.id_a3 <- phylosig(tree_a3,idiosyncrasy,
                   test=TRUE)
K.cf_a3 <- phylosig(tree_a3,cumulative_freq,
                   test=TRUE)
K.h_a3 <- phylosig(tree_a3,entropy,
                   test=TRUE)
K.r_a3 <- phylosig(tree_a3,redundancy,
                   test=TRUE)
```

```{r}
print(K.prod_a3)
plot(K.prod_a3)
```

```{r}
print(K.id_a3)
plot(K.id_a3)
```


```{r}
print(K.cf_a3)
plot(K.cf_a3)
```

```{r}
print(K.h_a3)
plot(K.h_a3)
```


```{r}
print(K.r_a3)
plot(K.r_a3)
```

## Further Robustness Study: 
Is the entropy/redundancy/cf really capturing an aspect of morphology? What happens if we train our models on corpora 
with far less morphology—unisent word lists.

```{r}
#Load the character data
file="../data/text_stats/lang_vecs_unisent_standardized.tsv"
chars2 <- read.delim(file)

#change a few language names so they correspond to the languages in reference tree
chars2[2,"lang"] <- "Tosk"
chars2[3,"lang"] <- "Eastern_Armenian"
chars2[9,"lang"] <- "Persian"
chars2[12,"lang"] <- "Modern_Greek"
chars2[28,"lang"] <- "Slovenian"
chars2[31,"lang"] <- "Ukrainian"
```


```{r}
#Isolate the relevant statistics
unisent_prod <- setNames(chars2$standardized_p,
                         chars2$lang)
unisent_cf <- setNames(chars2$standardized_cf,
                         chars2$lang)
unisent_id <- setNames(chars2$standardized_i,
                         chars2$lang)
unisent_h <- setNames(chars2$standardized_h,
                         chars2$lang)
unisent_r <- setNames(chars2$standardized_r,
                         chars2$lang)
```


```{r}
#Calculate Blomberg's K for each of our continuous variables
K.uni_prod <- phylosig(tree,unisent_prod,
                   test=TRUE)
K.uni_id <- phylosig(tree,unisent_id,
                   test=TRUE)
K.uni_cf <- phylosig(tree,unisent_cf,
                   test=TRUE)
K.uni_h <- phylosig(tree,unisent_h,
                   test=TRUE)
K.uni_r <- phylosig(tree,unisent_r,
                   test=TRUE)
```

```{r}
print(K.uni_prod)
```

```{r}
print(K.uni_id)
```

```{r}
print(K.uni_cf)
```


```{r}
print(K.uni_h)
```


```{r}
print(K.uni_r)
```
